# Generated by Django 5.0.3 on 2024-06-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('принят', 'Принят'), ('оплачен', 'Оплачен')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в_процессе', 'В процессе'), ('готов', 'Готов')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('менеджер', 'Менеджер'), ('сотрудник_обслуживания_номеров', 'Сотрудник обслуживания номеров'), ('сотрудник_предоставления_услуг', 'Сотрудник предоставления услуг отеля')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('работает', 'Работает'), ('уволен', 'Уволен')], default='работает', max_length=30),
        ),
    ]
